/**
 * Bundles each MCP Apps view (ui-src/*.ts) into one self contained HTML document: script,
 * styles and the Overpass font inlined, so any MCP Apps host (the simulated Echo Show today,
 * Alexa+ later) can render it in a sandboxed frame. Output: src/ui/generated/views.ts.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { build } from "esbuild";

const VIEWS = { warningSigns: "warning-signs" } as const;

const require = createRequire(import.meta.url);
const fontDir = dirname(require.resolve("@fontsource-variable/overpass/package.json"));
const font = readFileSync(join(fontDir, "files/overpass-latin-wght-normal.woff2")).toString(
  "base64",
);

const css = `@font-face{font-family:"Overpass";font-style:normal;font-display:block;font-weight:100 900;src:url(data:font/woff2;base64,${font}) format("woff2")}\n${readFileSync("ui-src/view.css", "utf8")}`;

async function bundle(file: string): Promise<string> {
  const result = await build({
    entryPoints: [`ui-src/${file}.ts`],
    bundle: true,
    format: "iife",
    minify: true,
    platform: "browser",
    target: "es2022",
    write: false,
    legalComments: "none",
  });
  return result.outputFiles[0]?.text ?? "";
}

const entries: string[] = [];
for (const [key, file] of Object.entries(VIEWS)) {
  const script = (await bundle(file)).replaceAll("</script", "<\\/script");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><main id="view" aria-live="polite" aria-busy="true"></main><script>${script}</script></body></html>`;
  entries.push(`  ${key}: ${JSON.stringify(html)},`);
  console.log(`${file}: ${(html.length / 1024).toFixed(0)} KB`);
}

mkdirSync("src/ui/generated", { recursive: true });
writeFileSync(
  "src/ui/generated/views.ts",
  `// Generated by scripts/build-views.ts. Do not edit by hand.\nexport const GENERATED_VIEWS = {\n${entries.join("\n")}\n} as const;\n`,
);
